
delete from province;
INSERT INTO `province` VALUES (1, '北京市', 1);
INSERT INTO `province` VALUES (2, '天津市', 1);
INSERT INTO `province` VALUES (3, '河北省', 1);
INSERT INTO `province` VALUES (4, '山西省', 1);
INSERT INTO `province` VALUES (5, '内蒙古自治区', 1);
INSERT INTO `province` VALUES (6, '辽宁省', 1);
INSERT INTO `province` VALUES (7, '吉林省', 1);
INSERT INTO `province` VALUES (8, '黑龙江省', 1);
INSERT INTO `province` VALUES (9, '上海市', 1);
INSERT INTO `province` VALUES (10, '江苏省', 1);
INSERT INTO `province` VALUES (11, '浙江省', 1);
INSERT INTO `province` VALUES (12, '安徽省', 1);
INSERT INTO `province` VALUES (13, '福建省', 1);
INSERT INTO `province` VALUES (14, '江西省', 1);
INSERT INTO `province` VALUES (15, '山东省', 1);
INSERT INTO `province` VALUES (16, '河南省', 1);
INSERT INTO `province` VALUES (17, '湖北省', 1);
INSERT INTO `province` VALUES (18, '湖南省', 1);
INSERT INTO `province` VALUES (19, '广东省', 1);
INSERT INTO `province` VALUES (20, '广西壮族自治区', 1);
INSERT INTO `province` VALUES (21, '海南省', 1);
INSERT INTO `province` VALUES (22, '重庆市', 1);
INSERT INTO `province` VALUES (23, '四川省', 1);
INSERT INTO `province` VALUES (24, '贵州省', 1);
INSERT INTO `province` VALUES (25, '云南省', 1);
INSERT INTO `province` VALUES (26, '西藏自治区', 1);
INSERT INTO `province` VALUES (27, '陕西省', 1);
INSERT INTO `province` VALUES (28, '甘肃省', 1);
INSERT INTO `province` VALUES (29, '青海省', 1);
INSERT INTO `province` VALUES (30, '宁夏回族自治区', 1);
INSERT INTO `province` VALUES (31, '新疆维吾尔自治区', 1);
INSERT INTO `province` VALUES (32, '香港特别行政区', 1);
INSERT INTO `province` VALUES (33, '澳门特别行政区', 1);
INSERT INTO `province` VALUES (34, '台湾省', 1);
update province p set p.faraway=1 where p.province_id in ('31','30' ,'26' ,'25' ,'28' ,'5' ,'21' ,'32'  ,'33','34' );