package co.legu.requirements.api.role.bo;

public class MenuBo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parnet
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    private Long parnet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parnet
     *
     * @return the value of menu.parnet
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public Long getParnet() {
        return parnet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parnet
     *
     * @param parnet the value for menu.parnet
     *
     * @mbggenerated Thu Mar 09 15:13:52 CST 2017
     */
    public void setParnet(Long parnet) {
        this.parnet = parnet;
    }
}