CREATE TABLE `link` (
  `id` CHAR(22) NOT NULL,
  `name` VARCHAR(50) DEFAULT NULL,
  `url` VARCHAR(100) DEFAULT NULL,
  `img` VARCHAR(100) DEFAULT NULL,
  `status` TINYINT(1) DEFAULT '1',
  `order` INT(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8;
